# -*- coding: utf-8 -*-
"""svm_kernels_tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDMWHt0Nw5jzUdqWBgtF8tJzKTa7QSsc

# How Different Kernels Change the Behaviour of SVM

**A Hands-On Tutorial**

---

This notebook provides a complete, runnable demonstration of how different kernel functions
transform the behaviour of Support Vector Machines (SVMs). All figures shown in the
accompanying tutorial are generated here.

**GitHub Repository**: *[Insert your GitHub repo link here]*

## References & Resources
1. Cortes, C. & Vapnik, V. (1995). Support-vector networks. *Machine Learning*, 20(3), 273-297.
2. Boser, B. E., Guyon, I. M., & Vapnik, V. N. (1992). A training algorithm for optimal margin classifiers. *COLT '92*.
3. Scholkopf, B. & Smola, A. J. (2002). *Learning with Kernels*. MIT Press.
4. Scikit-learn documentation: https://scikit-learn.org/stable/modules/svm.html
5. Hsu, C.-W., Chang, C.-C., & Lin, C.-J. (2003). A practical guide to support vector classification.
6. Raschka, S. (2015). *Python Machine Learning*. Packt Publishing.

---

## 1. Setup & Imports
"""

# Install dependencies (uncomment if needed)
# !pip install numpy matplotlib scikit-learn seaborn

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.colors import ListedColormap
import seaborn as sns
from sklearn import svm
from sklearn.datasets import make_moons, make_circles, load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
import os
import warnings
warnings.filterwarnings('ignore')

# Colourblind-friendly palette (Tol Bright)
CB_BLUE   = '#0077BB'
CB_ORANGE = '#EE7733'
CB_GREEN  = '#009988'
CB_RED    = '#CC3311'
CB_PURPLE = '#AA3377'
PALETTE = [CB_BLUE, CB_ORANGE, CB_GREEN, CB_RED, CB_PURPLE]
sns.set_palette(PALETTE)

# Dark plot style
plt.rcParams.update({
    'figure.facecolor': '#0f1117',
    'axes.facecolor':   '#181b25',
    'axes.edgecolor':   '#333',
    'axes.labelcolor':  '#ccc',
    'text.color':       '#ccc',
    'xtick.color':      '#999',
    'ytick.color':      '#999',
    'font.family':      'sans-serif',
    'font.size':        11,
    'axes.grid':        True,
    'grid.color':       '#2a2d3a',
    'grid.alpha':       0.6,
})

# Output directory
FIG_DIR = os.path.join('..', 'figures')
os.makedirs(FIG_DIR, exist_ok=True)
DPI = 180

print('Setup complete!')

"""## 2. Generate Synthetic Data

We use scikit-learn's `make_moons` and `make_circles` datasets. These are ideal for
demonstrating SVM kernels because:
- **Moons**: Two interleaving half-circles that are *not* linearly separable.
- **Circles**: One class enclosed within the other, requiring non-linear boundaries.

We also load the **Iris** dataset (sepal features only) for a real-world comparison.
"""

np.random.seed(42)

# Moons dataset
X_moons, y_moons = make_moons(n_samples=400, noise=0.25, random_state=42)
scaler_moons = StandardScaler()
X_moons = scaler_moons.fit_transform(X_moons)

# Circles dataset
X_circles, y_circles = make_circles(n_samples=400, noise=0.15, factor=0.5, random_state=42)
scaler_circles = StandardScaler()
X_circles = scaler_circles.fit_transform(X_circles)

# Iris dataset (first 2 features)
iris = load_iris()
X_iris = iris.data[:, :2]
y_iris = iris.target
scaler_iris = StandardScaler()
X_iris = scaler_iris.fit_transform(X_iris)

# Visualise the datasets
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
cmap2 = ListedColormap([CB_BLUE, CB_ORANGE])
cmap3 = ListedColormap([CB_BLUE, CB_ORANGE, CB_GREEN])

axes[0].scatter(X_moons[:, 0], X_moons[:, 1], c=y_moons, cmap=cmap2,
                edgecolors='#fff5', s=30)
axes[0].set_title('Moons Dataset', fontweight='bold', color='#fff')

axes[1].scatter(X_circles[:, 0], X_circles[:, 1], c=y_circles, cmap=cmap2,
                edgecolors='#fff5', s=30)
axes[1].set_title('Circles Dataset', fontweight='bold', color='#fff')

axes[2].scatter(X_iris[:, 0], X_iris[:, 1], c=y_iris, cmap=cmap3,
                edgecolors='#fff5', s=30)
axes[2].set_title('Iris (Sepal Features)', fontweight='bold', color='#fff')

fig.tight_layout()
plt.show()

"""## 3. Understanding SVMs — The Core Idea

A Support Vector Machine finds the **hyperplane** that maximises the **margin** between classes.
The data points closest to this boundary are called **support vectors** — they are the critical
samples that define the decision boundary.

### Mathematical Formulation

Given training data $(x_i, y_i)$ where $y_i \in \{-1, +1\}$, the SVM finds:

$$\min_{w,b} \frac{1}{2}\|w\|^2 \quad \text{subject to} \quad y_i(w \cdot x_i + b) \geq 1$$

The **kernel trick** allows SVMs to operate in higher-dimensional spaces *without*
explicitly transforming the data, via a kernel function $K(x_i, x_j) = \phi(x_i) \cdot \phi(x_j)$.
"""

# Visualise the SVM margin and support vectors with a linear kernel
np.random.seed(7)
X_lin = np.vstack([
    np.random.randn(30, 2) * 0.6 + np.array([1.5, 1.5]),
    np.random.randn(30, 2) * 0.6 + np.array([-1.5, -1.5]),
])
y_lin = np.array([0]*30 + [1]*30)
clf_lin = svm.SVC(kernel='linear', C=10)
clf_lin.fit(X_lin, y_lin)

fig, ax = plt.subplots(figsize=(7, 6))
h = 0.02
x_min, x_max = X_lin[:, 0].min() - 1, X_lin[:, 0].max() + 1
y_min, y_max = X_lin[:, 1].min() - 1, X_lin[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
Z = clf_lin.decision_function(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)

ax.contour(xx, yy, Z, levels=[-1, 0, 1],
           colors=[CB_ORANGE, '#fff', CB_BLUE],
           linewidths=[1.5, 2.5, 1.5], linestyles=['--', '-', '--'])
ax.contourf(xx, yy, Z, levels=[-1, 0, 1],
            colors=['#EE773318', '#0077BB18'], alpha=0.5)
cmap_pts2 = ListedColormap([CB_BLUE, CB_ORANGE])
ax.scatter(X_lin[:, 0], X_lin[:, 1], c=y_lin, cmap=cmap_pts2,
           edgecolors='#fff5', s=40, linewidths=0.5)
sv = clf_lin.support_vectors_
ax.scatter(sv[:, 0], sv[:, 1], s=140, facecolors='none',
           edgecolors=CB_ORANGE, linewidths=2, label='Support Vectors')
ax.annotate('Maximum Margin', xy=(0, 0), fontsize=12, color='#fff',
            fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.3', fc='#333', ec='#555', alpha=0.8))
ax.set_title('Linear SVM - Hyperplane & Margin', fontsize=14, fontweight='bold', color='#fff')
ax.legend(loc='upper left', fontsize=10, framealpha=0.3)
fig.savefig(os.path.join(FIG_DIR, 'svm_math_intuition.png'), dpi=DPI, bbox_inches='tight',
            facecolor=fig.get_facecolor())
plt.show()

"""## 4. The Four Kernels

| Kernel | Formula | Key Parameter(s) |
|--------|---------|-------------------|
| **Linear** | $K(x,y) = x \cdot y$ | C |
| **Polynomial** | $K(x,y) = (\gamma \, x \cdot y + r)^d$ | degree, coef0 |
| **RBF (Gaussian)** | $K(x,y) = \exp(-\gamma \|x-y\|^2)$ | gamma |
| **Sigmoid** | $K(x,y) = \tanh(\gamma \, x \cdot y + r)$ | gamma, coef0 |

Let us train each kernel on the moons dataset and visualise the decision boundaries.
"""

# Helper function for decision boundary visualisation
def plot_decision_boundary(ax, clf, X, y, title, cmap_bg=None, cmap_pts=None):
    if cmap_bg is None:
        cmap_bg = ListedColormap(['#0077BB30', '#EE773330'])
    if cmap_pts is None:
        cmap_pts = ListedColormap([CB_BLUE, CB_ORANGE])
    h = 0.02
    x_min, x_max = X[:, 0].min() - 0.8, X[:, 0].max() + 0.8
    y_min, y_max = X[:, 1].min() - 0.8, X[:, 1].max() + 0.8
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)
    ax.contourf(xx, yy, Z, alpha=0.35, cmap=cmap_bg, levels=1)
    ax.contour(xx, yy, Z, colors='#ffffff44', linewidths=0.8)
    ax.scatter(X[:, 0], X[:, 1], c=y, cmap=cmap_pts,
               edgecolors='#ffffff55', s=30, linewidths=0.5)
    if hasattr(clf, 'support_vectors_'):
        sv = clf.support_vectors_
        ax.scatter(sv[:, 0], sv[:, 1], s=100, facecolors='none',
                   edgecolors=CB_ORANGE, linewidths=1.5, label='Support Vectors')
    ax.set_title(title, fontsize=13, fontweight='bold', color='#fff')
    ax.set_xlim(x_min, x_max)
    ax.set_ylim(y_min, y_max)
    ax.tick_params(labelsize=8)

print('Helper function defined.')

# Define kernel configurations
kernels_cfg = {
    'linear':  {'kernel': 'linear', 'C': 1.0},
    'poly':    {'kernel': 'poly', 'degree': 3, 'C': 1.0, 'coef0': 1},
    'rbf':     {'kernel': 'rbf', 'gamma': 'scale', 'C': 1.0},
    'sigmoid': {'kernel': 'sigmoid', 'gamma': 'scale', 'coef0': 0, 'C': 1.0},
}

# 4-panel comparison
fig, axes = plt.subplots(2, 2, figsize=(12, 10))
for ax, (k_name, k_params) in zip(axes.ravel(), kernels_cfg.items()):
    clf = svm.SVC(**k_params)
    clf.fit(X_moons, y_moons)
    acc = accuracy_score(y_moons, clf.predict(X_moons))
    plot_decision_boundary(ax, clf, X_moons, y_moons,
                           f'{k_name.capitalize()} Kernel  (acc={acc:.2f})')

fig.suptitle('Kernel Comparison on Moons Dataset', fontsize=16,
             fontweight='bold', color='#fff', y=0.98)
fig.tight_layout(rect=[0, 0, 1, 0.95])
fig.savefig(os.path.join(FIG_DIR, 'kernel_comparison_grid.png'), dpi=DPI,
            bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

"""### Observations

- **Linear**: Draws a straight line. Fails to capture the curved moon shapes.
- **Polynomial (degree 3)**: Creates a curved boundary that better follows the data.
- **RBF**: The most flexible; produces smooth, tight boundaries around each class.
- **Sigmoid**: Similar to a neural network's activation; sometimes produces unexpected boundaries.

## 5. Individual Kernel Decision Boundaries

Let us look at each kernel in more detail.
"""

for k_name, k_params in kernels_cfg.items():
    clf = svm.SVC(**k_params)
    clf.fit(X_moons, y_moons)
    fig, ax = plt.subplots(figsize=(6, 5))
    plot_decision_boundary(ax, clf, X_moons, y_moons,
                           f'{k_name.capitalize()} Kernel')
    ax.legend(loc='upper right', fontsize=9, framealpha=0.3)
    fig.savefig(os.path.join(FIG_DIR, f'decision_boundary_{k_name}.png'),
                dpi=DPI, bbox_inches='tight', facecolor=fig.get_facecolor())
    plt.show()
    print(f'{k_name.capitalize()}: {accuracy_score(y_moons, clf.predict(X_moons)):.3f} accuracy')
    print(f'  Support vectors: {len(clf.support_vectors_)}')
    print()

"""## 6. Parameter Tuning Deep Dive

### 6.1 Effect of Gamma (RBF Kernel)

The `gamma` parameter defines how far the influence of a single training example reaches:
- **Low gamma** = far reach = smoother boundary (underfitting risk)
- **High gamma** = close reach = tighter boundary (overfitting risk)
"""

gammas = [0.1, 0.5, 1.0, 5.0, 10.0, 50.0]
fig, axes = plt.subplots(2, 3, figsize=(15, 9))
for ax, g in zip(axes.ravel(), gammas):
    clf = svm.SVC(kernel='rbf', gamma=g, C=1.0)
    clf.fit(X_moons, y_moons)
    acc = accuracy_score(y_moons, clf.predict(X_moons))
    plot_decision_boundary(ax, clf, X_moons, y_moons,
                           f'gamma = {g}  (acc={acc:.2f})')
fig.suptitle('Effect of Gamma on RBF Kernel', fontsize=16,
             fontweight='bold', color='#fff', y=0.98)
fig.tight_layout(rect=[0, 0, 1, 0.95])
fig.savefig(os.path.join(FIG_DIR, 'gamma_effect.png'), dpi=DPI,
            bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

"""### 6.2 Effect of Regularisation Parameter C

The `C` parameter controls the trade-off between a smooth decision boundary and classifying training points correctly:
- **Low C** = wider margin, more misclassifications allowed (underfitting)
- **High C** = narrow margin, fewer misclassifications (overfitting)
"""

C_values = [0.01, 0.1, 1, 10, 100, 1000]
fig, axes = plt.subplots(2, 3, figsize=(15, 9))
for ax, c in zip(axes.ravel(), C_values):
    clf = svm.SVC(kernel='rbf', gamma='scale', C=c)
    clf.fit(X_moons, y_moons)
    acc = accuracy_score(y_moons, clf.predict(X_moons))
    plot_decision_boundary(ax, clf, X_moons, y_moons,
                           f'C = {c}  (acc={acc:.2f})')
fig.suptitle('Effect of Regularisation Parameter C (RBF Kernel)', fontsize=16,
             fontweight='bold', color='#fff', y=0.98)
fig.tight_layout(rect=[0, 0, 1, 0.95])
fig.savefig(os.path.join(FIG_DIR, 'C_regularization.png'), dpi=DPI,
            bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

"""### 6.3 Effect of Polynomial Degree

Higher polynomial degrees allow more complex boundaries but increase overfitting risk.
"""

degrees = [2, 3, 4, 5, 6, 7]
fig, axes = plt.subplots(2, 3, figsize=(15, 9))
for ax, d in zip(axes.ravel(), degrees):
    clf = svm.SVC(kernel='poly', degree=d, C=1.0, coef0=1)
    clf.fit(X_moons, y_moons)
    acc = accuracy_score(y_moons, clf.predict(X_moons))
    plot_decision_boundary(ax, clf, X_moons, y_moons,
                           f'Degree = {d}  (acc={acc:.2f})')
fig.suptitle('Effect of Polynomial Degree', fontsize=16,
             fontweight='bold', color='#fff', y=0.98)
fig.tight_layout(rect=[0, 0, 1, 0.95])
fig.savefig(os.path.join(FIG_DIR, 'polynomial_degree_effect.png'), dpi=DPI,
            bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

"""## 7. Quantitative Comparison

Let us split the data into train/test sets and compare kernel performance rigorously.
"""

X_tr, X_te, y_tr, y_te = train_test_split(
    X_moons, y_moons, test_size=0.3, random_state=42
)

print('Dataset split: {} train, {} test\n'.format(len(X_tr), len(X_te)))

accs_train, accs_test = {}, {}
for k_name, k_params in kernels_cfg.items():
    clf = svm.SVC(**k_params)
    clf.fit(X_tr, y_tr)
    accs_train[k_name] = accuracy_score(y_tr, clf.predict(X_tr))
    accs_test[k_name]  = accuracy_score(y_te, clf.predict(X_te))
    print(f'{k_name.capitalize():>8}  |  Train: {accs_train[k_name]:.3f}  |  Test: {accs_test[k_name]:.3f}')
    print(classification_report(y_te, clf.predict(X_te), target_names=['Class 0', 'Class 1']))

# Accuracy bar chart
fig, ax = plt.subplots(figsize=(8, 5))
x_pos = np.arange(len(accs_train))
w = 0.35
bars1 = ax.bar(x_pos - w/2, accs_train.values(), w, label='Train',
               color=CB_BLUE, edgecolor='#fff3', linewidth=0.6)
bars2 = ax.bar(x_pos + w/2, accs_test.values(), w, label='Test',
               color=CB_ORANGE, edgecolor='#fff3', linewidth=0.6)
ax.set_xticks(x_pos)
ax.set_xticklabels([k.capitalize() for k in accs_train.keys()])
ax.set_ylabel('Accuracy')
ax.set_ylim(0.5, 1.05)
ax.set_title('Train vs Test Accuracy by Kernel', fontsize=14,
             fontweight='bold', color='#fff')
ax.legend(framealpha=0.3)
for b in bars1:
    ax.text(b.get_x() + b.get_width()/2, b.get_height() + 0.01,
            f'{b.get_height():.2f}', ha='center', va='bottom', fontsize=9, color='#ccc')
for b in bars2:
    ax.text(b.get_x() + b.get_width()/2, b.get_height() + 0.01,
            f'{b.get_height():.2f}', ha='center', va='bottom', fontsize=9, color='#ccc')
fig.savefig(os.path.join(FIG_DIR, 'accuracy_comparison.png'), dpi=DPI,
            bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

# Confusion matrices
fig, axes = plt.subplots(1, 4, figsize=(16, 4))
for ax, (k_name, k_params) in zip(axes, kernels_cfg.items()):
    clf = svm.SVC(**k_params)
    clf.fit(X_tr, y_tr)
    cm = confusion_matrix(y_te, clf.predict(X_te))
    sns.heatmap(cm, annot=True, fmt='d', cmap='YlOrBr', ax=ax,
                cbar=False, linewidths=1, linecolor='#333',
                annot_kws={'fontsize': 14, 'fontweight': 'bold'})
    ax.set_title(f'{k_name.capitalize()}', fontsize=12, fontweight='bold', color='#fff')
    ax.set_xlabel('Predicted', fontsize=10)
    ax.set_ylabel('Actual', fontsize=10)
fig.suptitle('Confusion Matrices (Test Set)', fontsize=14,
             fontweight='bold', color='#fff', y=1.02)
fig.tight_layout()
fig.savefig(os.path.join(FIG_DIR, 'confusion_matrices.png'), dpi=DPI,
            bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

"""## 8. Real-World Application: Iris Dataset

Let us apply the same kernel comparison to the classic Iris dataset (using only the two sepal features for visualisation).
"""

fig, axes = plt.subplots(2, 2, figsize=(12, 10))
cmap_bg3 = ListedColormap(['#0077BB25', '#EE773325', '#00998825'])
cmap_pt3 = ListedColormap([CB_BLUE, CB_ORANGE, CB_GREEN])

for ax, (k_name, k_params) in zip(axes.ravel(), kernels_cfg.items()):
    clf = svm.SVC(**k_params)
    clf.fit(X_iris, y_iris)
    acc = accuracy_score(y_iris, clf.predict(X_iris))
    plot_decision_boundary(ax, clf, X_iris, y_iris,
                           f'{k_name.capitalize()} (acc={acc:.2f})',
                           cmap_bg=cmap_bg3, cmap_pts=cmap_pt3)

fig.suptitle('Kernel Comparison on Iris Dataset (Sepal Features)',
             fontsize=16, fontweight='bold', color='#fff', y=0.98)
fig.tight_layout(rect=[0, 0, 1, 0.95])
fig.savefig(os.path.join(FIG_DIR, 'iris_kernels.png'), dpi=DPI,
            bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

"""## 9. Circles Dataset — Where Linear Fails

The circles dataset is a perfect example of why non-linear kernels matter: the inner class
is completely enclosed by the outer class, making linear separation impossible.
"""

fig, axes = plt.subplots(2, 2, figsize=(12, 10))
for ax, (k_name, k_params) in zip(axes.ravel(), kernels_cfg.items()):
    clf = svm.SVC(**k_params)
    clf.fit(X_circles, y_circles)
    acc = accuracy_score(y_circles, clf.predict(X_circles))
    plot_decision_boundary(ax, clf, X_circles, y_circles,
                           f'{k_name.capitalize()} Kernel  (acc={acc:.2f})')
fig.suptitle('Kernel Comparison on Circles Dataset', fontsize=16,
             fontweight='bold', color='#fff', y=0.98)
fig.tight_layout(rect=[0, 0, 1, 0.95])
fig.savefig(os.path.join(FIG_DIR, 'circles_comparison.png'), dpi=DPI,
            bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

"""## 10. Ethical Considerations

When deploying SVMs in practice, consider:

1. **Bias in training data**: SVMs learn from data — biased data produces biased models.
2. **Interpretability**: Non-linear kernels create complex boundaries that are harder to explain.
3. **Fairness**: Always audit model performance across different demographic groups.
4. **Privacy**: Support vectors are actual data points — releasing them could compromise privacy.

## 11. Summary & Key Takeaways

| Aspect | Linear | Polynomial | RBF | Sigmoid |
|--------|--------|-----------|-----|--------|
| **Best for** | Linearly separable data | Moderate non-linearity | Complex non-linear data | Specific use cases |
| **Speed** | Fast | Moderate | Moderate | Moderate |
| **Overfitting risk** | Low | Medium (degree) | Medium-High (gamma) | Varies |
| **Key parameter** | C | degree, coef0 | gamma | gamma, coef0 |

**Golden rule**: Start with RBF (it is the most versatile), then try simpler kernels if you
need faster training or better interpretability.

---

*Tutorial GitHub Repository*: [Insert link here]

*License*: MIT
"""